name: iOS証明書作成ヘルパー

on:
  workflow_dispatch:

jobs:
  create-certificate-request:
    name: 証明書署名要求（CSR）の作成
    runs-on: macos-latest

    steps:
      - name: 証明書署名要求を作成
        run: |
          echo "=== iOS Distribution証明書の作成手順 ==="

          # 一時的なキーペアを生成
          openssl genrsa -out BottleKeep_Distribution.key 2048

          # CSR（証明書署名要求）を生成
          openssl req -new -key BottleKeep_Distribution.key -out BottleKeep_Distribution.csr \
            -subj "/C=JP/ST=Tokyo/L=Tokyo/O=BottleKeep/CN=BottleKeep Distribution"

          echo "CSRファイルが作成されました！"

          echo ""
          echo "次の手順："
          echo "1. 下記のCSRファイルをダウンロード"
          echo "2. Apple Developer Portal > Certificates で新規証明書を作成"
          echo "3. 'Apple Distribution' を選択"
          echo "4. CSRファイルをアップロード"
          echo "5. 作成された証明書(.cer)をダウンロード"

      - name: CSRファイルをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: certificate-signing-request
          path: |
            BottleKeep_Distribution.csr
            BottleKeep_Distribution.key

      - name: Apple Developer Portal手順ガイド
        run: |
          cat << 'EOF'
          ========================================
          Apple Developer Portal での証明書作成手順
          ========================================

          1. https://developer.apple.com にアクセス
          2. Account > Certificates, IDs & Profiles をクリック
          3. Certificates > + ボタンをクリック
          4. "Apple Distribution" を選択
          5. ダウンロードしたCSRファイルを選択してアップロード
          6. 作成された証明書(.cer)をダウンロード

          ========================================
          証明書のP12ファイル変換手順（macOS環境が必要）
          ========================================

          1. ダウンロードした証明書(.cer)をダブルクリックでキーチェーンに追加
          2. キーチェーンアクセスを開く
          3. 追加された証明書を選択
          4. 右クリック > 書き出し
          5. ファイル形式で "個人情報交換 (.p12)" を選択
          6. パスワードを設定して保存

          このP12ファイルがGitHub ActionsのBUILD_CERTIFICATE_BASE64に必要です
          EOF

  conversion-helper:
    name: 証明書変換ヘルパー（macOS環境必要）
    runs-on: macos-latest
    needs: create-certificate-request

    steps:
      - name: 変換手順の説明
        run: |
          echo "証明書を.p12形式に変換するためのmacOS環境です"
          echo ""
          echo "手動での変換手順："
          echo "1. Apple Developer Portalから.cerファイルをダウンロード"
          echo "2. .cerファイルをダブルクリックしてキーチェーンに追加"
          echo "3. 以下のコマンドでp12ファイルを作成："
          echo ""
          echo "security find-identity -v -p codesigning"
          echo "# 上記で表示された証明書のSHA-1を使用"
          echo ""
          echo "security export -k ~/Library/Keychains/login.keychain -t identities -f pkcs12 -P 'YOUR_PASSWORD' -o BottleKeep_Distribution.p12"

          # テスト用の空のp12ファイルを作成（実際の証明書ではない）
          echo "テスト用のファイル構造を作成中..."

      - name: P12変換スクリプトを作成
        run: |
          cat > convert_cert.sh << 'EOF'
          #!/bin/bash

          echo "iOS証明書をP12形式に変換します"
          echo "前提: Apple Developer Portalから証明書(.cer)をダウンロード済み"
          echo ""

          if [ ! -f "BottleKeep_Distribution.cer" ]; then
            echo "エラー: BottleKeep_Distribution.cer ファイルが見つかりません"
            echo "Apple Developer Portalから証明書をダウンロードして、このファイル名で保存してください"
            exit 1
          fi

          echo "証明書をキーチェーンに追加中..."
          security import BottleKeep_Distribution.cer -k ~/Library/Keychains/login.keychain

          echo "P12ファイルを作成中..."
          echo "パスワードを入力してください（GitHub Secretsに設定するパスワード）:"
          read -s password

          security export -k ~/Library/Keychains/login.keychain \
            -t identities \
            -f pkcs12 \
            -P "$password" \
            -o BottleKeep_Distribution.p12

          echo "P12ファイルが作成されました: BottleKeep_Distribution.p12"
          echo ""
          echo "Base64エンコード用コマンド:"
          echo "base64 -i BottleKeep_Distribution.p12 | pbcopy"
          EOF

          chmod +x convert_cert.sh

      - name: 変換スクリプトをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: certificate-conversion-script
          path: convert_cert.sh