name: iOS シンプルビルドテスト

on:
  workflow_dispatch: # 手動実行のみ

jobs:
  simple-build:
    name: シンプルビルドテスト
    runs-on: macos-14

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Xcodeバージョンを設定
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          xcodebuild -version

      - name: Swift Package情報を確認
        run: |
          echo "=== Swift Package情報を確認 ==="
          swift package describe --type json || echo "Package.swift確認"
          cat Package.swift

          echo "=== 利用可能なターゲットを確認 ==="
          swift package show-dependencies || echo "依存関係なし"

      - name: Swift Packageビルドテスト
        run: |
          echo "=== Swift Packageビルドテスト ==="
          swift build --target BottleKeeper || echo "Swift Package Manager ビルドに失敗"

      - name: xcodebuildを使用したビルドテスト
        run: |
          echo "=== xcodebuildを使用してSwift Packageを直接ビルド ==="

          # Swift Packageから直接ビルド
          xcodebuild build \
            -scheme BottleKeeper \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -configuration Debug \
            -skipPackagePluginValidation \
            || echo "xcodebuildビルドに失敗しましたが、続行します"

      - name: 詳細ログ表示
        if: always()
        run: |
          echo "=== 最終的な構造確認 ==="
          find . -name "*.xcodeproj" -exec ls -la {} \;

          echo "=== Swift Package情報 ==="
          swift package describe --type json | jq '.' || echo "jqが利用できません"

      - name: 証明書設定テスト
        run: |
          echo "=== GitHub Secrets確認 ==="
          echo "BUILD_CERTIFICATE_BASE64 length: ${#BUILD_CERTIFICATE_BASE64}"
          echo "P12_PASSWORD length: ${#P12_PASSWORD}"
          echo "TEAM_ID: $TEAM_ID"

          if [ -n "$BUILD_CERTIFICATE_BASE64" ]; then
            echo "✅ 証明書Secret設定済み"
          else
            echo "❌ 証明書Secretが設定されていません"
          fi
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}