name: SecretsшинхоЪчв║шкН

on:
  workflow_dispatch: # цЙЛхЛХхоЯшбМуБоуБ┐

jobs:
  check-secrets:
    name: SecretsшинхоЪчК╢ц│Бчв║шкН
    runs-on: ubuntu-latest

    steps:
      - name: SecretsшинхоЪчК╢ц│БуВТчв║шкН
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          echo "=== GitHub SecretsшинхоЪчК╢ц│Б ==="
          echo ""

          # ши╝цШОцЫ╕щЦвщАг
          echo "ЁЯУ▒ iOSч╜▓хРНши╝цШОцЫ╕щЦвщАг:"
          if [ -n "$BUILD_CERTIFICATE_BASE64" ]; then
            echo "тЬЕ BUILD_CERTIFICATE_BASE64: шинхоЪц╕ИуБ┐ (щХ╖уБХ: ${#BUILD_CERTIFICATE_BASE64}цЦЗхнЧ)"
          else
            echo "тЭМ BUILD_CERTIFICATE_BASE64: цЬкшинхоЪ"
          fi

          if [ -n "$P12_PASSWORD" ]; then
            echo "тЬЕ P12_PASSWORD: шинхоЪц╕ИуБ┐ (щХ╖уБХ: ${#P12_PASSWORD}цЦЗхнЧ)"
          else
            echo "тЭМ P12_PASSWORD: цЬкшинхоЪ"
          fi

          if [ -n "$BUILD_PROVISION_PROFILE_BASE64" ]; then
            echo "тЬЕ BUILD_PROVISION_PROFILE_BASE64: шинхоЪц╕ИуБ┐ (щХ╖уБХ: ${#BUILD_PROVISION_PROFILE_BASE64}цЦЗхнЧ)"
          else
            echo "тЭМ BUILD_PROVISION_PROFILE_BASE64: цЬкшинхоЪ"
          fi

          if [ -n "$KEYCHAIN_PASSWORD" ]; then
            echo "тЬЕ KEYCHAIN_PASSWORD: шинхоЪц╕ИуБ┐ (щХ╖уБХ: ${#KEYCHAIN_PASSWORD}цЦЗхнЧ)"
          else
            echo "тЭМ KEYCHAIN_PASSWORD: цЬкшинхоЪ"
          fi

          if [ -n "$TEAM_ID" ]; then
            echo "тЬЕ TEAM_ID: шинхоЪц╕ИуБ┐ (хАд: $TEAM_ID)"
          else
            echo "тЭМ TEAM_ID: цЬкшинхоЪ"
          fi

          echo ""
          echo "ЁЯФС App Store Connect APIщЦвщАг:"
          if [ -n "$APP_STORE_CONNECT_API_KEY_ID" ]; then
            echo "тЬЕ APP_STORE_CONNECT_API_KEY_ID: шинхоЪц╕ИуБ┐ (хАд: $APP_STORE_CONNECT_API_KEY_ID)"
          else
            echo "тЭМ APP_STORE_CONNECT_API_KEY_ID: цЬкшинхоЪ"
          fi

          if [ -n "$APP_STORE_CONNECT_ISSUER_ID" ]; then
            echo "тЬЕ APP_STORE_CONNECT_ISSUER_ID: шинхоЪц╕ИуБ┐ (хАд: $APP_STORE_CONNECT_ISSUER_ID)"
          else
            echo "тЭМ APP_STORE_CONNECT_ISSUER_ID: цЬкшинхоЪ"
          fi

          if [ -n "$APP_STORE_CONNECT_API_KEY" ]; then
            echo "тЬЕ APP_STORE_CONNECT_API_KEY: шинхоЪц╕ИуБ┐ (щХ╖уБХ: ${#APP_STORE_CONNECT_API_KEY}цЦЗхнЧ)"
          else
            echo "тЭМ APP_STORE_CONNECT_API_KEY: цЬкшинхоЪ"
          fi

          echo ""
          echo "=== шинхоЪхоМф║Жх║ж ==="

          # х┐ЕщаИSecretsуБоцХ░уВТуВлуВжуГ│уГИ
          required_secrets=8
          set_secrets=0

          [ -n "$BUILD_CERTIFICATE_BASE64" ] && ((set_secrets++))
          [ -n "$P12_PASSWORD" ] && ((set_secrets++))
          [ -n "$BUILD_PROVISION_PROFILE_BASE64" ] && ((set_secrets++))
          [ -n "$KEYCHAIN_PASSWORD" ] && ((set_secrets++))
          [ -n "$TEAM_ID" ] && ((set_secrets++))
          [ -n "$APP_STORE_CONNECT_API_KEY_ID" ] && ((set_secrets++))
          [ -n "$APP_STORE_CONNECT_ISSUER_ID" ] && ((set_secrets++))
          [ -n "$APP_STORE_CONNECT_API_KEY" ] && ((set_secrets++))

          echo "шинхоЪц╕ИуБ┐: $set_secrets / $required_secrets"

          if [ $set_secrets -eq $required_secrets ]; then
            echo "ЁЯОЙ уБЩуБ╣уБжуБоSecretsуБМшинхоЪц╕ИуБ┐уБзуБЩя╝Б"
            echo "TestFlightшЗкхЛХщЕНф┐буБоц║ЦхВЩуБМцХ┤уБДуБ╛уБЧуБЯуАВ"
          else
            echo "тЪая╕П $(($required_secrets - $set_secrets))хАЛуБоSecretsуБМцЬкшинхоЪуБзуБЩуАВ"
            echo "ф╕КшиШуБотЭМщаЕчЫоуВТшинхоЪуБЧуБжуБПуБауБХуБДуАВ"
          fi