name: テストビルド

on:
  workflow_dispatch: # 手動実行のみ

jobs:
  test-build:
    name: プロジェクト構造確認とテストビルド
    runs-on: macos-14

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Xcodeバージョンを設定
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app
          xcodebuild -version

      - name: プロジェクト構造を確認
        run: |
          echo "=== プロジェクト構造の確認 ==="
          ls -la
          echo ""
          echo "=== BottleKeeperディレクトリ ==="
          ls -la BottleKeeper/
          echo ""
          echo "=== Swiftファイルの検索 ==="
          find . -name "*.swift" | head -10
          echo ""
          echo "=== Info.plistの確認 ==="
          find . -name "Info.plist"

      - name: Package.swiftの確認
        run: |
          echo "=== Package.swiftの内容 ==="
          if [ -f "Package.swift" ]; then
            cat Package.swift
          else
            echo "Package.swiftが見つかりません"
          fi

      - name: Swift Packageとしてビルドテスト
        run: |
          echo "=== Swift Package としてビルドテスト ==="
          if [ -f "Package.swift" ]; then
            swift build || echo "Swift buildに失敗しました"
            swift test || echo "Swift testに失敗しました"
          else
            echo "Package.swiftが存在しないため、Swift Packageビルドをスキップします"
          fi

      - name: 手動でXcodeプロジェクトを作成
        run: |
          echo "=== 手動でXcodeプロジェクトを作成 ==="

          # 基本的なiOSアプリプロジェクトの作成
          mkdir -p BottleKeeper.xcodeproj

          # project.pbxprojファイルの基本構造を作成
          cat > BottleKeeper.xcodeproj/project.pbxproj << 'EOF'
          // !$*UTF8*$!
          {
            archiveVersion = 1;
            classes = {
            };
            objectVersion = 56;
            objects = {
              /* Build configuration list for PBXProject "BottleKeeper" */
              1DEB928508733DD80010E9CD /* Build configuration list for PBXProject "BottleKeeper" */ = {
                isa = XCConfigurationList;
                buildConfigurations = (
                  1DEB928608733DD80010E9CD /* Debug */,
                  1DEB928708733DD80010E9CD /* Release */,
                );
                defaultConfigurationIsVisible = 0;
                defaultConfigurationName = Release;
              };
              /* Build configuration list for PBXNativeTarget "BottleKeeper" */
              1DEB928908733DD80010E9CD /* Build configuration list for PBXNativeTarget "BottleKeeper" */ = {
                isa = XCConfigurationList;
                buildConfigurations = (
                  1DEB928A08733DD80010E9CD /* Debug */,
                  1DEB928B08733DD80010E9CD /* Release */,
                );
                defaultConfigurationIsVisible = 0;
                defaultConfigurationName = Release;
              };
            };
            rootObject = 29B97313FDCFA39411CA2CEA /* Project object */;
          }
          EOF

          echo "基本的なXcodeプロジェクト構造を作成しました"

      - name: 最終的な構造確認
        run: |
          echo "=== 最終的なプロジェクト構造 ==="
          ls -la
          echo ""
          echo "=== 作成されたファイル ==="
          find . -name "*.xcodeproj" -o -name "Package.swift" -o -name "*.swift" | head -20